const mongoose = require('mongoose');

const partialsentenceSchema = new mongoose.Schema({
    partialNumber: {
        type: String,
        minlength: [1, 'This is autogenerated, relax mongo does not auto generate'],
        default: 1
    },

    partialsentenceBody: {
        type: String,
        required: [true, 'Just build a random sentence...'],
    },

    partialNoun: {
        type: String,
    },

    partialAdverb: {
        type: String
    },

    partialAdjective: {
        type: String
    },

    partialConjunction: {
        type: String
    },

    partialDeterminer: {
        type: String
    },

    partialExclamation: {
        type: String
    },

    partialPreposition: {
        type: String
    },

    partialPronoun: {
        type: String
    },

    partialVerb: {
        type: String
    },

    isComplete: {
        type: Boolean
    },

    updatedAt: {
        type: Date,
    },

    createdAt: {
        type: Date,
        required: true,
        default: Date.now
    },

})

partialsentenceSchema.pre("save", async function (next) {
    if (!this.isModified("partialsentenceBody")) {
        this.updatedAt = Date.now;
        next;
    }

    this.updatedAt = Date.now();
    // this.sentenceNumber = 1;
});

module.exports = mongoose.model("PartialSentence", partialsentenceSchema);
