const mongoose = require('mongoose');

const partialsentenceSchema = new mongoose.Schema({
    partialNumber: {
        type: String,
        minlength: [1, 'This is autogenerated, relax.'],
        default: 1
    },

    partialsentenceBody: {
        type: String,
        required: [true, 'Just build a random sentence...'],
    },

    updatedAt: {
        type: Date,
    },

    createdAt: {
        type: Date,
        required: true,
        default: Date.now
    },

})

partialsentenceSchema.pre("save", async function (next) {
    if (!this.isModified("partialsentenceBody")) {
        this.updatedAt = Date.now;
        next;
    }

    this.updatedAt = Date.now();
    // this.sentenceNumber = 1;
});

module.exports = mongoose.model("PartialSentence", partialsentenceSchema);
